### ISSUE TITLE
New field 'enabled' in State

### ISSUE THREAD

**Issue by hjw2015** [jm-73/pyIndego#110]
My scripts stopped working due to a new field named 'enabled' in the state class.

It's a bit unclear why/what this field actually means (or if it is also an issue for other users). But beside that the package just stops to work in this case - IMHO it should not  fail in case of a new unknown field.

**Comment by Fuempel** [comment]
Adding 2 lines in states.py fixes the problem for the moment, see commented line:

```
@nested_dataclass
class GenericData:
    """Generic Data Class."""

    alm_name: str = None
    alm_sn: str = None
    service_counter: int = None
    needs_service: bool = None
    alm_mode: str = None
    bareToolnumber: str = None
    alm_firmware_version: str = None
    model_description: str = None
    model_voltage: ModelVoltage = field(default_factory=ModelVoltage)
    mowing_mode_description: str = None
    renew_date: str = None  # ADD THIS LINE
```

```
@nested_dataclass
class State:
    """State Class."""

    state: int = None
    map_update_available: bool = None
    mowed: int = None
    mowmode: int = None
    error: int = None
    xPos: int = None
    yPos: int = None
    charge: int = None
    operate: int = None
    runtime: Runtime = field(default_factory=Runtime)
    mapsvgcache_ts: int = None
    svg_xPos: int = None
    svg_yPos: int = None
    config_change: bool = None
    mow_trig: bool = None
    enabled: bool = None   # ADD THIS LINE
```

**Comment by MagaliDB** [comment]
Can confirm that Fuempel his fix works; I've applied it to my forked repository and no longer have any errors regarding those fields.

**Comment by Windmelodie** [comment]
> Can confirm that Fuempel his fix works; I've applied it to my forked repository and no longer have any errors regarding those fields.

How do you get the forked repository work on your HA?

i would like to try in addition to `enabled`
in line 182, add
`self.renew_date = convert_bosch_datetime(self.renew_date)`

in line 170, add
`renew_date: datetime = None`

which should save the date in correct format.  But anyway I dont know what is the meaning of this renew date and it is not implemented in Indego reository

**Comment by jm-73** [comment]
I have build a new version of the python library used by the Bosch integration. Please try this change in your config/custom_components/indego/manifest.json:

"requirements": ["pyIndego==2.0.29"],

change to

"requirements": ["pyIndego==2.0.30"],

Please let me know if it works for you!

/J

**Comment by jm-73** [comment]
New version of component released. Should be visible in HACS shortly.
